[package]
name = "bevy_car_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_engine = "6.0.0"


[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-check= false
incremental =false
codegen-units = 16